build:docker_image:
  stage: build
  image: docker:20.10
  tags: [dot-2highcpu]
  allow_failure: false
  rules:
        - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - cp $DOTENV .env
    - docker build
      --progress plain
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}
      --file Dockerfile
      .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}

deploy:update_service:
    stage: deploy
    image: python:3.10.12
    tags: [dot]
    allow_failure: false
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    variables:
        STACK_NAME: 'nextjs-fullstack'
        SERVICE_NAME: 'landing-page'
        URL_APP: 'https://nextjs-fullstack-blrplt.dot.co.id'
        CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}${CI_COMMIT_SHORT_SHA}
    script:
        - pip install -r deploy/script/requirement.txt
        - python deploy/script/develop.py