export const MOCK_STUDIOS = {
  data: [
    {
      id: "1",
      name: "Studio 1",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "2",
      name: "Studio 2",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "3",
      name: "Studio 3",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "4",
      name: "Studio 4",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "5",
      name: "Studio 5",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "6",
      name: "Studio 6",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "7",
      name: "Studio 7",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "8",
      name: "Studio 8",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "9",
      name: "Studio 9",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "10",
      name: "Studio 10",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "11",
      name: "Studio 11",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "12",
      name: "Studio 12",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "13",
      name: "Studio 13",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "14",
      name: "Studio 14",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "15",
      name: "Studio 15",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "16",
      name: "Studio 16",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "17",
      name: "Studio 17",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "18",
      name: "Studio 18",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "19",
      name: "Studio 19",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "20",
      name: "Studio 20",
      capacity: 100,
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
  ],
  meta: {
    page: 1,
    perPage: 5,
    total: 20,
    totalPage: Math.ceil(20 / 5),
  },
};
