export const MOCK_FILMS = {
  data: [
    {
      id: "1",
      title: "The Shawshank Redemption",
      duration: 142,
      description:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      poster: "https://placehold.co/200x300?text=The+Shawshank+Redemption",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "2",
      title: "The Godfather",
      duration: 175,
      description:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      poster: "https://placehold.co/200x300?text=The+Godfather",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "3",
      title: "The Dark Knight",
      duration: 152,
      description:
        "When the menace known as the Joker wreaks havoc and chaos, Batman must accept his greatest psychological and physical tests.",
      poster: "https://placehold.co/200x300?text=The+Dark+Knight",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "4",
      title: "Pulp Fiction",
      duration: 154,
      description:
        "The lives of two hitmen, a boxer, a gangster, and his wife intertwine in a series of incidents.",
      poster: "https://placehold.co/200x300?text=Pulp+Fiction",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "5",
      title: "Schindler's List",
      duration: 195,
      description:
        "In German-occupied Poland during World War II, a man becomes an unlikely savior of over a thousand Jews.",
      poster: "https://placehold.co/200x300?text=Schindler's+List",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "6",
      title: "Forrest Gump",
      duration: 142,
      description:
        "The story of a man with a low IQ who achieves incredible feats and witnesses significant historical events.",
      poster: "https://placehold.co/200x300?text=Forrest+Gump",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "7",
      title: "Inception",
      duration: 148,
      description:
        "A thief uses dream-sharing technology to implant an idea into the mind of a target.",
      poster: "https://placehold.co/200x300?text=Inception",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "8",
      title: "Fight Club",
      duration: 139,
      description:
        "An insomniac office worker forms an underground fight club that evolves into something much bigger.",
      poster: "https://placehold.co/200x300?text=Fight+Club",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "9",
      title: "The Matrix",
      duration: 136,
      description:
        "A computer hacker learns the true nature of his reality and his role in the war against its controllers.",
      poster: "https://placehold.co/200x300?text=The+Matrix",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "10",
      title: "Goodfellas",
      duration: 146,
      description: "The rise and fall of a mob associate as he lives his life in the Mafia.",
      poster: "https://placehold.co/200x300?text=Goodfellas",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "11",
      title: "Se7en",
      duration: 127,
      description:
        "Two detectives hunt for a serial killer who uses the seven deadly sins as his modus operandi.",
      poster: "https://placehold.co/200x300?text=Se7en",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "12",
      title: "The Silence of the Lambs",
      duration: 118,
      description:
        "A young FBI trainee seeks the help of a brilliant yet psychopathic serial killer to catch another.",
      poster: "https://placehold.co/200x300?text=The+Silence+of+the+Lambs",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "13",
      title: "Saving Private Ryan",
      duration: 169,
      description:
        "Following the Normandy Landings, a group of soldiers search for a paratrooper behind enemy lines.",
      poster: "https://placehold.co/200x300?text=Saving+Private+Ryan",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "14",
      title: "The Green Mile",
      duration: 189,
      description:
        "A death row corrections officer witnesses supernatural events linked to a condemned man.",
      poster: "https://placehold.co/200x300?text=The+Green+Mile",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "15",
      title: "Interstellar",
      duration: 169,
      description:
        "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
      poster: "https://placehold.co/200x300?text=Interstellar",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "16",
      title: "The Lion King",
      duration: 88,
      description:
        "A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
      poster: "https://placehold.co/200x300?text=The+Lion+King",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "17",
      title: "Gladiator",
      duration: 155,
      description:
        "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.",
      poster: "https://placehold.co/200x300?text=Gladiator",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "18",
      title: "The Prestige",
      duration: 130,
      description: "Two magicians become bitter rivals as they compete for fame and fortune.",
      poster: "https://placehold.co/200x300?text=The+Prestige",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "19",
      title: "Django Unchained",
      duration: 165,
      description:
        "With the help of a German bounty hunter, a freed slave sets out to rescue his wife.",
      poster: "https://placehold.co/200x300?text=Django+Unchained",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    {
      id: "20",
      title: "The Departed",
      duration: 151,
      description:
        "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang.",
      poster: "https://placehold.co/200x300?text=The+Departed",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
  ],
  meta: {
    page: 1,
    perPage: 10,
    total: 20,
    totalPage: Math.ceil(20 / 10),
  },
};
